const logoMeta = {
  alan: { displayName: "Alan AI" },
  aws: { displayName: "AWS" },
  amd: { displayName: "AMD" },
  cpp: { displayName: "C++" },
  csharp: { displayName: "C#" },
  css: { displayName: "CSS" },
  louisvuitton: { displayName: "Louis Vuitton" },
  jnj: { displayName: "Johnson & Johnson" },
  ts: { displayName: "TypeScript" },
  js: { displayName: "JavaScript" },
  php: { displayName: "php" },
  kfc: { displayName: "KFC" },
  reactnative: { displayName: "React Native" },
  buymeacoffee: { displayName: "Buy Me a Coffee" },
  bmw: { displayName: "BMW" },
  burgerking: { displayName: "BurgerKing" },
  hsbc: { displayName: "HSBC" },
  phonepe: { displayName: "PhonePe" },
  rayban: { displayName: "Ray-Ban" },
  mysql: { displayName: "MySQL" },
  opensea: { displayName: "OpenSea" },
  orcid: { displayName: "ORCID" },
  html: { displayName: "HTML" },
  jquery: { displayName: "jQuery" },
  mui: { displayName: "MUI" },
  clickup: { displayName: "ClickUp" },
  hnm: { displayName: "H&M" },
  freefire: { displayName: "FreeFire" },
  sekiro: {
    displayName: "Sekiro: Shadows Die Twice",
  },
  mahindra: { displayName: "Mahindra", url: "https://mahindra.com" },
  iitb: { displayName: "IIT Bombay", url: "https://iitb.ac.in" },
  iitm: { displayName: "IIT Madras", url: "https://iitm.ac.in" },
  iitk: { displayName: "IIT Kanpur", url: "https://iitk.ac.in" },
};

export default logoMeta;
